FROM golang:1.22-alpine

WORKDIR /app

# Install golangci-lint
RUN apk add --no-cache curl && \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2

COPY go.mod ./
COPY .golangci.yml ./
COPY *.go ./

# Command to run linter and tests
CMD ["sh", "-c", "golangci-lint run -v && go test -v -cover ./..."]
